apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f production.yml convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: django
  name: django
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: django
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f production.yml convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: django
    spec:
      containers:
        - args:
            - /start
          env:
            - name: DJANGO_ACCOUNT_ALLOW_REGISTRATION
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_ACCOUNT_ALLOW_REGISTRATION
                  name: envs--production--django
            - name: DJANGO_ADMIN_URL
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_ADMIN_URL
                  name: envs--production--django
            - name: DJANGO_ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_ALLOWED_HOSTS
                  name: envs--production--django
            - name: DJANGO_AWS_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_AWS_ACCESS_KEY_ID
                  name: envs--production--django
            - name: DJANGO_AWS_SECRET_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_AWS_SECRET_ACCESS_KEY
                  name: envs--production--django
            - name: DJANGO_AWS_STORAGE_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_AWS_STORAGE_BUCKET_NAME
                  name: envs--production--django
            - name: DJANGO_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_SECRET_KEY
                  name: envs--production--django
            - name: DJANGO_SECURE_SSL_REDIRECT
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_SECURE_SSL_REDIRECT
                  name: envs--production--django
            - name: DJANGO_SERVER_EMAIL
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_SERVER_EMAIL
                  name: envs--production--django
            - name: DJANGO_SETTINGS_MODULE
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_SETTINGS_MODULE
                  name: envs--production--django
            - name: MAILGUN_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: MAILGUN_API_KEY
                  name: envs--production--django
            - name: MAILGUN_DOMAIN
              valueFrom:
                configMapKeyRef:
                  key: MAILGUN_DOMAIN
                  name: envs--production--django
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: envs--production--postgres
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST
                  name: envs--production--postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: envs--production--postgres
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PORT
                  name: envs--production--postgres
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: envs--production--postgres
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  key: REDIS_URL
                  name: envs--production--django
            - name: WEB_CONCURRENCY
              valueFrom:
                configMapKeyRef:
                  key: WEB_CONCURRENCY
                  name: envs--production--django
          image: kanban_backend_production_django
          name: django
          resources: {}
      restartPolicy: Always
status: {}
